name: manajemen_rumah_sakit_cli_2
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  intl: ^0.18.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
